services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - "./redis:/data"

  redisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - 8000:80
    environment:
      REDIS_1_HOST: redis
