services:
  redis:
    profiles:
      - dev
      - local
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - einsbym-network

  redisinsight:
    profiles:
      - dev
      - local
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    networks:
      - einsbym-network

  einsbym-database:
    profiles:
      - dev
      - local
    image: postgres:alpine
    container_name: einsbym-database
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: einsbym
      PGTZ: America/Recife
    ports:
      - "5432:5432"
    networks:
      - einsbym-network

  einsbym-api:
    profiles:
      - local
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: einsbym-api
    depends_on:
      - einsbym-database
      - redis
    environment:
      DB_HOST: einsbym-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: einsbym
      DB_SYNCRONIZE: false

      SERVER_PORT: 4000
      JWT_SECRET: wowlookatmyamazingsecretkey
      
      EINSBYM_STORAGE: http://einsbym-storage:8080/storage-service
      
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 4000:4000
    networks:
      - einsbym-network

networks:
  einsbym-network:

volumes:
  database:
