services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - einsbym-network

  redisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - 8000:80
    environment:
      REDIS_1_HOST: redis
    networks:
      - einsbym-network

  einsbym-database:
    image: postgres:alpine
    container_name: einsbym-database
    volumes:
      - einsbym-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: einsbym
    ports:
      - "5432:5432"
    networks:
      - einsbym-network

  einsbym-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: einsbym-api
    depends_on:
      - einsbym-database
      - redis
    environment:
      DB_HOST: einsbym-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: einsbym
      DB_SYNCRONIZE: false
      SERVER_PORT: 4000
      JWT_SECRET: wowlookatmyamazingsecretkey
      EINSBYM_STORAGE: einsbym-api-gateway/storage-service
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 4000:4000
    networks:
      - einsbym-network

networks:
  einsbym-network:
    driver: bridge
    external: true

volumes:
  einsbym-database-data:
