services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data

  redisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - 8000:80
    environment:
      REDIS_1_HOST: redis
    networks:
      - einsbym-network

  einsbym-database:
    image: postgres:alpine
    container_name: einsbym-database
    volumes:
      - einsbym-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: einsbym
    ports:
      - "5000:5432"
    networks:
      - einsbym-network

  einsbym-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - einsbym-database
    environment:
      DB_HOST: einsbym-database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: einsbym
      DB_SYNCRONIZE: true
      SERVER_PORT: 4000
      JWT_SECRET: wowlookatmyamazingsecretkey
      EINSBYM_STORAGE: http://localhost:8080/storage-service
    networks:
      - einsbym-network
    ports:
      - 3000:3000

networks:
  einsbym-network:
    driver: bridge
    external: true

volumes:
  einsbym-database-data:
