services:
  db:
    image: postgres:15.3
    container_name: db
    environment:
      POSTGRES_DB: einsbym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - network
    ports:
        - 5433:5432   

  einsbym-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: einsbym
      DB_USER: postgres
      DB_PASSWORD: root
      DB_SYNCHRONIZE: false
      REDIS_PORT: 6379
      REDIS_HOST: localhost
      JWT_SECRET: dgdfafdhafdhsdfh
      EINSBYM_STORAGE: http://localhost:8080/storage-service

    depends_on:
      - db
    networks:
      - network
    ports:
      - 3000:3000

networks:
  network:
    driver: bridge

volumes:
  postgres:
  