name: Build Workflow

on:
    push:
        branches: ['develop', 'main', 'feature/*']
    pull_request:
        branches: ['develop', 'main', 'feature/*']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install

            - name: Build NestJS app
              run: npm run build
